export const USER_SET_CITY = 'USER_SET_CITY'
export const REQUEST_AD = 'REQUEST_AD'
export const RECEIVE_AD = 'RECEIVE_AD'
export const REQUEST_LIKES = 'REQUEST_LIKES'
export const RECEVIE_LIKES = 'RECEVIE_LIKES'